version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    container_name: express-test-mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 27018:27017
    volumes:
      - mongodb_container:/data/db

  apis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_container:
