let constants = {
    ID: "id",
    UID: "uid",
    NAME: "name",
    FIRST: "first",
    MIDDLE: "middle",
    LAST: "last",
    EMAIL: "email",
    EMAIL_ADDRESS: "email_address",
    PASSWORD: "password",
    PASSWORD_SALT: "password_salt",
    OLD_PASSWORD: "old_password",
    NEW_PASSWORD: "new_password",
    IMAGE: "image",
    OAUTH_CODE: "oauth_code",
    STATUS: "status",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    USER: "user",
    CURRENT_USER: "current_user",
    ACCESS_TOKEN: "access_token",
    REFRESH_TOKEN: "refresh_token",
    TOKEN: "token",
    SESSION_MANAGEMENT: "session_management",
    IS_EXPIRED: "is_expired",
    EXPIRY_TIME: "expiry_time",
    PURPOSE: "purpose",
    GOOGLE: "google",
    FACEBOOK: "facebook",
    APPLE: "apple",
    PAGE: "page",
    LIMIT: "limit",
    REGISTRATION_CHANNEL: "registration_channel"
}

export default constants;
